FROM gradle:jdk11 as gradleimage
COPY . /home/gradle/source
WORKDIR /home/gradle/source
RUN gradle buildFatJar

FROM openjdk:11-jre-slim
COPY --from=gradleimage /home/gradle/source/build/libs/TwitterVideoDownloadBot-1.0-SNAPSHOT.jar /app/
WORKDIR /app
ENTRYPOINT ["java", "-jar", "TwitterVideoDownloadBot-1.0-SNAPSHOT.jar"]